"use client";

import React, { useState } from "react";
import { Terminal, Copy, Check } from "lucide-react";

interface SetupGuideProps {
  steps: string[];
}

export default function SetupGuide({ steps }: SetupGuideProps) {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const handleCopy = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  return (
    <div className="flex-grow overflow-y-auto p-8 custom-scrollbar">
      <div className="max-w-4xl mx-auto space-y-8">
        {/* Header Description */}
        <section className="glass-panel p-6 rounded-lg">
          <div className="flex items-center gap-3 mb-4">
            <span className="material-symbols-outlined text-secondary">terminal</span>
            <h2 className="font-headline-sm text-headline-sm text-primary">
              Local Installation Guide
            </h2>
          </div>
          <p className="font-body-md text-on-surface-variant leading-relaxed">
            The following setup procedures have been generated by parsing the build configuration and project structure dependencies. Run these steps sequentially to setup a local environment.
          </p>
        </section>

        {/* Installation Steps */}
        <section className="space-y-4">
          {steps.length === 0 ? (
            <div className="text-center p-8 border-base rounded bg-[#18181B] font-mono text-[#A1A1AA]">
              No configuration files parsed to deduce installation guides.
            </div>
          ) : (
            steps.map((step, index) => (
              <div
                key={index}
                className="bg-[#18181B] border border-outline-variant rounded-lg p-5 flex flex-col gap-3 relative group hover:border-[#6366F1]/30 transition-all duration-300"
              >
                {/* Step indicator */}
                <div className="flex items-center gap-2">
                  <div className="w-5 h-5 rounded-full bg-secondary/15 flex items-center justify-center border border-secondary/30">
                    <span className="text-xs font-bold text-secondary font-mono">{index + 1}</span>
                  </div>
                  <span className="font-semibold text-primary text-sm font-sans">Procedure Step</span>
                </div>

                {/* Step Text / Code Block */}
                <div className="flex items-start justify-between bg-[#09090B] border-base p-4 rounded text-code-md font-mono leading-relaxed text-[#A1A1AA] select-all">
                  <div className="pr-4">{step}</div>
                  <button
                    onClick={() => handleCopy(step, index)}
                    className="p-1 text-on-surface-variant hover:text-white hover:bg-surface-container rounded transition-colors shrink-0 outline-none"
                    title="Copy step command"
                  >
                    {copiedIndex === index ? (
                      <Check className="w-4 h-4 text-emerald-400" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                </div>
              </div>
            ))
          )}
        </section>
      </div>
    </div>
  );
}
